### ISSUE TITLE
FindCountryByName does not support official names

### ISSUE THREAD

**Issue by aaronmcohen** [pariz/gountries#11]
```go
gountries.New().FindCountryByName("United States of America") 
```
does not return a country where this does
```go
gountries.New().FindCountryByName("United States") 
```
"United States of America" should be valid based on https://github.com/pariz/gountries/blob/9f809e356e5cc61e570a77e6b7fe5f5eafab3576/data/yaml/countries/us.yaml#L3

```yaml
name:
  common: United States
  official: United States of America
```

Please extend this method to include official and native text. 

Thank you!
